Creating Arrays

In [1]:
import numpy as np

list1= [23, 56, 78, 43, 69]
set1= set(list1)
tuple1= (1, 2, 3)
array1 = np.array(list1)
array2 = np.array(tuple1)
array3 = np.array(set1)

print(array1)
print(array2)
print(array3)

[23 56 78 43 69]
[1 2 3]
{69, 43, 78, 23, 56}


Array Dimensions

In [2]:
arr1 = np.array(50)

print(arr1)
print("The array's dimension is : ", arr1.ndim)

50
The array's dimension is :  0


In [3]:
arr2 = np.array([1, 2, 3])

print(arr2)
print("The array's dimension is : ", arr2.ndim)

[1 2 3]
The array's dimension is :  1


In [4]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr3)
print("The array's dimension is : ", arr3.ndim)

[[1 2 3]
 [4 5 6]]
The array's dimension is :  2


In [5]:
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr4)

print("The array's dimension is : ", arr4.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
The array's dimension is :  3


In [6]:
arr5 = np.array([1, 2, 3, 4], ndmin=6)

print(arr5)
print('number of dimensions :', arr5.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions : 6


Array Reshaping

In [7]:
import numpy as np

arr6 = np.array([[10, 20, 30], [2, 4, 5]])

print(arr6)

print("\nThe array's shape is : ", arr6.shape)

arr6.shape = (3,2)

print("\n",arr6)

print("\nThe new array's shape is : ", arr6.shape)

[[10 20 30]
 [ 2  4  5]]

The array's shape is :  (2, 3)

 [[10 20]
 [30  2]
 [ 4  5]]

The new array's shape is :  (3, 2)


In [8]:
import numpy as np

arr6 = np.array([[10, 20, 30], [2, 4, 5]])

print(arr6)

print("\nThe array's shape is : ", arr6.shape)

arr6 = arr6.reshape(3,2)

print("\n",arr6)

print("\nThe new array's shape is : ", arr6.shape)

[[10 20 30]
 [ 2  4  5]]

The array's shape is :  (2, 3)

 [[10 20]
 [30  2]
 [ 4  5]]

The new array's shape is :  (3, 2)


Array Datatype

In [9]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [10]:
arr1 = np.array([1.0, 2.0, 6,7])
arr2 = np.array([1, 2, 3, 4], dtype='S')

print(arr1, "The data type for array1 is: ",arr1.dtype)
print(arr2, "The data type for array2 is: ",arr2.dtype)

[1. 2. 6. 7.] The data type for array1 is:  float64
[b'1' b'2' b'3' b'4'] The data type for array2 is:  |S1


Array Index

In [11]:
a = np.array([[1,2], [3, 4], [5, 6]])

result1 = a[[0, 1, 2], [0, 1, 0]]
result2 = np.array([a[0, 0], a[1, 1], a[2, 0]])
print(result1) 
print(result2)  

result3 = a[[0, 0], [1, 1]]
result4 = np.array([a[0, 1], a[0, 1]])
print("\n",result3)  
print(result4)  

[1 4 5]
[1 4 5]

 [2 2]
[2 2]


Slicing

In [12]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("array a\n", a)
b = a[:2, 1:3]
print("\narray b\n",b)
b[0, 0] = 77 
print("\nUpdated array b : \n",b)
print("\n Updated array a\n",a)
print("\n",a[0, 1])         

array a
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

array b
 [[2 3]
 [6 7]]

Updated array b : 
 [[77  3]
 [ 6  7]]

 Updated array a
 [[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 77


Boolean Array Indexing

In [13]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   

print(bool_idx)      

print("\n",a[bool_idx])  
print("\n",a[a > 2])  

[[False False]
 [ True  True]
 [ True  True]]

 [3 4 5 6]

 [3 4 5 6]


Sorting Array

In [14]:
arr1 = np.array([67, 54, 87, 6, 12, 4])
arr2 = np.array(['banana', 'cherry', 'apple'])
arr3 = np.array([True , False, True])

print("The sorted array 1 : ",np.sort(arr1))
print("The sorted array 2 : ",np.sort(arr2))
print("The sorted array 3 : ",np.sort(arr3))

The sorted array 1 :  [ 4  6 12 54 67 87]
The sorted array 2 :  ['apple' 'banana' 'cherry']
The sorted array 3 :  [False  True  True]


Filtering

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filtered_arr = arr % 2 == 0

new_arr = arr[filtered_arr]

print(filtered_arr)
print(new_arr)

[False  True False  True False  True False]
[2 4 6]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filtered_arr = []

for element in arr:
 
  if element % 2 == 0:
    filtered_arr.append(True)
  else:
    filtered_arr.append(False)

newarr = arr[filtered_arr]

print(filtered_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


Masking

In [17]:
import numpy as np

numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)

print(numbers)
mask = numbers % 4 == 0
print("\n",mask)
print("\n",numbers[mask])

[[ 5  6  8 10 12 14]
 [16 18 20 22 24 26]
 [28 30 32 34 36 38]
 [40 42 44 46 48 50]]

 [[False False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]]

 [ 8 12 16 20 24 28 32 36 40 44 48]


Array Stacking

In [18]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = np.hstack((a,b)) 
d = np.vstack((a,b))
e = np.dstack((a,b))
f = np.column_stack((a,b))
g = np.concatenate((a,b))
print(" The Horizontally Stacked array is : ",c," with shape", c.shape, "and dimension", c.ndim)
print("\n The vertically Stacked array is : ",d,"with shape", d.shape, "and dimension" , d.ndim)
print("\n The Depth Stacked array is : ",e,"with shape", e.shape, "and dimension ", e.ndim)
print("\n The Column Stacked array is : ",f,"with shape", f.shape, "and dimension ", f.ndim)
print("\n The concatenated array is : ",g,"with shape", g.shape, "and dimension ", g.ndim)

 The Horizontally Stacked array is :  [ 1  2  3  4 10 20 30 40]  with shape (8,) and dimension 1

 The vertically Stacked array is :  [[ 1  2  3  4]
 [10 20 30 40]] with shape (2, 4) and dimension 2

 The Depth Stacked array is :  [[[ 1 10]
  [ 2 20]
  [ 3 30]
  [ 4 40]]] with shape (1, 4, 2) and dimension  3

 The Column Stacked array is :  [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]] with shape (4, 2) and dimension  2

 The concatenated array is :  [ 1  2  3  4 10 20 30 40] with shape (8,) and dimension  1


Array Splitting

In [19]:
a = np.array([1,2,3,4,10,20,30,40]) 

c = np.split(a,2) 
d = np.array_split(a,2)
e = np.hsplit(a,4)

print(c)
print(d)
print(e,"\n")

[array([1, 2, 3, 4]), array([10, 20, 30, 40])]
[array([1, 2, 3, 4]), array([10, 20, 30, 40])]
[array([1, 2]), array([3, 4]), array([10, 20]), array([30, 40])] 



In [20]:
b = np.array([[23, 56, 78, 50], [12, 58, 67, 47]])
Split1 = np.split(b,[1,3])
Split2 = np.array_split(b,3)
Split3 = np.vsplit(b,2)
Split4 = np.hsplit(b,2)
Split5 = np.array_split(b,np.where(b[:,0]==12)[0][0])
print("1: ", Split1)
print("2: ", Split2)
print("3: ", Split3)
print("4: ", Split4)
print("5: ", Split5)

1:  [array([[23, 56, 78, 50]]), array([[12, 58, 67, 47]]), array([], shape=(0, 4), dtype=int64)]
2:  [array([[23, 56, 78, 50]]), array([[12, 58, 67, 47]]), array([], shape=(0, 4), dtype=int64)]
3:  [array([[23, 56, 78, 50]]), array([[12, 58, 67, 47]])]
4:  [array([[23, 56],
       [12, 58]]), array([[78, 50],
       [67, 47]])]
5:  [array([[23, 56, 78, 50],
       [12, 58, 67, 47]])]


In [21]:
a = np.array([[[23, 56, 78, 50], [12, 58, 67, 47],
               [34, 67, 89, 69], [12, 7, 68, 23]]])

Split1 = np.dsplit(a, [2,3])

print("1: ", Split1)

1:  [array([[[23, 56],
        [12, 58],
        [34, 67],
        [12,  7]]]), array([[[78],
        [67],
        [89],
        [68]]]), array([[[50],
        [47],
        [69],
        [23]]])]


NO copy

In [22]:
a = np.array([1,2,3,4,10,20,30,40])
A_id=id(a)
print("Array a :")
print(A_id)
print(a, "\n")
b = a
B_id=id(b)
print("Array b")
print(B_id)
print(b, "\n")

b[4:] = 0
print("New array b:",b)

print("New array a:",a)

Array a :
140576336433584
[ 1  2  3  4 10 20 30 40] 

Array b
140576336433584
[ 1  2  3  4 10 20 30 40] 

New array b: [1 2 3 4 0 0 0 0]
New array a: [1 2 3 4 0 0 0 0]


Shallowed Copy

In [23]:
a = np.array([1,2,3,4,10,20,30,40])

print("Array a :")
print(id(a))
print(a, "\n")

b = a.view()
print("Array b")
print(id(b))
print(b, "\n")

b[4:] = 0
print("New array b:",b)

print("New array a:",a)

Array a :
140576372387344
[ 1  2  3  4 10 20 30 40] 

Array b
140576372387728
[ 1  2  3  4 10 20 30 40] 

New array b: [1 2 3 4 0 0 0 0]
New array a: [1 2 3 4 0 0 0 0]


Base

In [24]:
a = np.array([1,2,3,4,10,20,30,40])

print("Array a :")
print(id(a))
print(a, "\n")

b = a.view()
print("Array b")
print(id(b))
print(b, "\n")

c = a.copy()
print("Array b")
print(id(c))
print(c, "\n")

print("base for a:",a.base)
print("base for b:",b.base)
print("base for c", c.base)

Array a :
140576336448080
[ 1  2  3  4 10 20 30 40] 

Array b
140576336446640
[ 1  2  3  4 10 20 30 40] 

Array b
140576336446832
[ 1  2  3  4 10 20 30 40] 

base for a: None
base for b: [ 1  2  3  4 10 20 30 40]
base for c None


Deep Copy

In [25]:
a = np.array([1,2,3,4,10,20,30,40])

print("Array a :")
print(id(a))
print(a, "\n")

b = a.copy()
print("Array b")
print(id(b))
print(b, "\n")

b[4:] = 0
print("New array b:",b)

print("New array a:",a)

Array a :
140576372543280
[ 1  2  3  4 10 20 30 40] 

Array b
140576372539440
[ 1  2  3  4 10 20 30 40] 

New array b: [1 2 3 4 0 0 0 0]
New array a: [ 1  2  3  4 10 20 30 40]


Phython special functions

In [26]:
import numpy as np

a = np.zeros((2,2))   
print(" np.zeros array result : \n",a) 

b = np.ones((1,2))    
print("\n np.ones array result : \n",b) 

c = np.full((2,2), 7)  
print("\n np.full array result : \n",c)

d = np.eye(2)         
print("\nnp.eye array result : \n",d )   

e = np.random.random((2,2))  
print("\n np.random array result : \n",e) 

 np.zeros array result : 
 [[0. 0.]
 [0. 0.]]

 np.ones array result : 
 [[1. 1.]]

 np.full array result : 
 [[7 7]
 [7 7]]

np.eye array result : 
 [[1. 0.]
 [0. 1.]]

 np.random array result : 
 [[0.94791524 0.99932138]
 [0.81110785 0.72917141]]


Basic Mathematical operations on array

In [27]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
print("\n",x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
print("\n",x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
print(x / y)
print("\n",np.divide(x, y))

# Elementwise square root; produces the array
print("\n",np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]

 [[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

 [[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [29]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
d = a + b
print(c)
print(d)

[ 10  40  90 160]
[11 22 33 44]


Matrix Operation

In [30]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product 
print("\n\n",x.dot(v))
print("\n",np.dot(x, v))

# Matrix / matrix product
print("\n\n",x.dot(y))
print("\n",np.dot(x, y))

219
219


 [29 67]

 [29 67]


 [[19 22]
 [43 50]]

 [[19 22]
 [43 50]]


In [31]:
x = np.array([[1,2],[3,4]])

print(np.sum(x)) 
print("\n",np.sum(x, axis=0))  
print("\n",np.sum(x, axis=1))  

10

 [4 6]

 [3 7]


In [32]:
x = np.array([[1,2], [3,4]])
print(x)    
print("\n",x.T)  

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print("\n\n",v)    
print("\n",v.T)  

[[1 2]
 [3 4]]

 [[1 3]
 [2 4]]


 [1 2 3]

 [1 2 3]


Broadcasting

In [33]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [34]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [35]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting

In [ ]:
v = np.array([1,2,3])  
w = np.array([4,5])    

v1 = np.reshape(v, (3, 1))
print(v1 * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
print("\nSummed value \n " ,x + v)

# Add a vector to each column of a matrix
print("\nx transpose \n ",x.T)
sum1 = (x.T + w)
print("\nsummed value\n",sum1)
# or.
print("\nAnswer 2\n",x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
print("\nproduct value\n",x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]

Summed value 
  [[2 4 6]
 [5 7 9]]

x transpose 
  [[1 4]
 [2 5]
 [3 6]]

summed value
 [[ 5  9]
 [ 6 10]
 [ 7 11]]

Answer 2
 [[ 5  6  7]
 [ 9 10 11]]

product value
 [[ 2  4  6]
 [ 8 10 12]]


iterating array

In [ ]:
a =np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
  
print('Original array is:\n')
print(a)
print()
 
print('Modified array is:\n')
 
# iterating  an array
for x in np.nditer(a):
    print(x)


Original array is:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Modified array is:

0
1
2
3
4
5
6
7
8
9
10
11




```
Random Sampling

In [ ]:
out_arr = np.random.randint(low = 0, high = 3, size = 5)
print (out_arr)

[1 1 0 2 2]


In [ ]:
out_arr = np.random.random_sample(size =(1,3))
print (out_arr) 

[[0.46732664 0.42324568 0.35847323]]


In [ ]:
out_arr = np.random.ranf(size =(2, 1))
print (out_arr)

[[0.82552119]
 [0.38060144]]


In [37]:
out_arr = np.random.random_integers(low = 3, size =(3, 3))
print(out_arr) 

[[3 1 2]
 [2 1 2]
 [3 3 1]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  """Entry point for launching an IPython kernel.


In [47]:
out_arr=np.random.randint(1, 8)
print(out_arr)

6
